const fs=require('fs');
function patch(path){let s=fs.readFileSync(path,'utf8');if(!s.includes('skill_execution_sandbox'))throw new Error(`sandbox declaration missing: ${path}`);const marker='else if (name === "skill_benchmark_runner")';if(!s.includes(marker))throw new Error(`runner dispatcher missing: ${path}`);const sandboxBranch=`else if (name === "skill_execution_sandbox") toolResult = await universalSkillExecutionSandboxManager(args?.action || "validate", args || {}, { execute: async (command,meta) => {\n    if (typeof callLocalBridge !== 'function') throw new Error('local execution bridge unavailable');\n    const isolation = { level: meta?.backend === 'docker' ? 'container-isolated' : 'process-isolated', backend: meta?.backend || 'process', network: 'disabled' };\n    const raw = await callLocalBridge('cmd', { command, timeoutMs: meta?.timeoutMs, workingDirectory: meta?.workingDirectory });\n    return { ...raw, isolation };\n} });\n`;
if(!s.includes('else if (name === "skill_execution_sandbox")'))s=s.replace(marker,sandboxBranch+marker);
const runnerOld='else if (name === "skill_benchmark_runner") toolResult = await universalSkillBenchmarkRunnerManager(args?.action || "run", args || {}, { execute: async (command,meta) => {\n                    if (typeof callLocalBridge !== \'function\') throw new Error(\'local execution bridge unavailable\');\n                    return await callLocalBridge(\'cmd\', { command, timeoutMs: meta?.timeoutMs });\n                } });';
const runnerNew='else if (name === "skill_benchmark_runner") toolResult = await universalSkillBenchmarkRunnerManager(args?.action || "run", args || {}, { execute: async (command,meta) => {\n                    if (typeof universalSkillExecutionSandboxManager !== \'function\') throw new Error(\'sandbox manager unavailable\');\n                    const isolated = await universalSkillExecutionSandboxManager(\'execute\',{ command, allowCommand:true, timeoutMs:meta?.timeoutMs, backend: meta?.sandbox?.backend || (path.includes(\'Mastermind_Desktop\') ? \'process\' : \'docker\'), processIsolation:\'required\'}, { execute: async (cmd,smeta) => {\n                        if (typeof callLocalBridge !== \'function\') throw new Error(\'local execution bridge unavailable\');\n                        const raw=await callLocalBridge(\'cmd\',{command:cmd,timeoutMs:smeta?.timeoutMs,workingDirectory:smeta?.workingDirectory});\n                        return { ...raw, isolation:{ level:smeta?.backend===\'docker\'?\'container-isolated\':\'process-isolated\', backend:smeta?.backend, network:\'disabled\' } };\n                    }});\n                    const ev=isolated?.evidence||{}; return {success:isolated?.ok!==false,exitCode:ev.exitCode,output:ev.output,isolation:ev.isolation,stdout:ev.output};\n                } });';
if(s.includes(runnerOld))s=s.replace(runnerOld,runnerNew);else if(!s.includes('processIsolation:\'required\''))throw new Error(`runner dispatcher pattern not found: ${path}`);
fs.writeFileSync(path,s);}
patch('my_AI/ai_engine_core.js');patch('Mastermind_Desktop/core.js');
console.log('sandbox isolation dispatchers patched');
