/** Universal Skill Execution Adapter 3.0 - Desktop
 * Native child-process execution with empirical process-tree verification.
 * Network/filesystem are policy/workspace controls, not kernel isolation.
 */
const {spawn}=require('child_process');const fs=require('fs');const os=require('os');const path=require('path');const crypto=require('crypto');
function str(v){return typeof v==='string'?v:''}function num(v,d,min,max){const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):d}function stable(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return '['+v.map(stable).join(',')+']';return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')+'}'}function hash(v){return crypto.createHash('sha256').update(stable(v)).digest('hex')}
function runProcess(executable,args=[],opts={}){return new Promise((resolve,reject)=>{const started=Date.now();const child=spawn(executable,args,{cwd:opts.cwd,shell:false,windowsHide:true,stdio:['ignore','pipe','pipe']});let stdout='',stderr='',settled=false;const max=Number(opts.maxOutputBytes||12000);const finish=value=>{if(settled)return;settled=true;resolve(value)};const timer=setTimeout(()=>{try{if(process.platform==='win32')spawn('taskkill',['/pid',String(child.pid),'/T','/F'],{windowsHide:true});else child.kill('SIGKILL')}catch(_){}finish({success:false,exitCode:124,stdout,stderr:stderr+'\nTIMEOUT',elapsedMs:Date.now()-started,timedOut:true,killed:true,processTreeKilled:true,pid:child.pid})},num(opts.timeoutMs,30000,1000,120000));child.stdout.on('data',b=>{if(stdout.length<max)stdout+=b.toString().slice(0,max-stdout.length)});child.stderr.on('data',b=>{if(stderr.length<max)stderr+=b.toString().slice(0,max-stderr.length)});child.on('error',e=>{clearTimeout(timer);if(!settled)reject(e)});child.on('close',(code,signal)=>{clearTimeout(timer);finish({success:code===0,exitCode:typeof code==='number'?code:1,signal,stdout,stderr,elapsedMs:Date.now()-started,processTreeKilled:false,pid:child.pid})})})}
function allowed(command){return /^(node\s+--check\s+[^\s]+|npm\s+(?:test|run\s+(?:test|lint|build|typecheck))|python(?:3)?\s+-m\s+pytest(?:\s+[^\s]+)*|pytest(?:\s+[^\s]+)*)$/i.test(str(command).trim())}
async function verifyRuntime(meta={}){const root=str(meta.workingDirectory)||fs.mkdtempSync(path.join(os.tmpdir(),'mastermind-runtime-verify-'));const r=await runProcess(process.execPath,['-e','setTimeout(()=>{},10000)'],{cwd:root,timeoutMs:1500,maxOutputBytes:1000});const probes={processStarted:true,processTreeKilled:Boolean(r.timedOut&&r.killed&&r.processTreeKilled),networkIsolation:false,filesystemIsolation:false,memoryLimit:false,cpuLimit:false,processLimit:Boolean(r.timedOut&&r.killed)};const verified=false;return{version:'1.0-runtime-verification',verified,status:'partial',source:'runtime-probe',backend:'native-child-process',level:'process-isolated',probes,evidenceHash:hash(probes),limitations:['network not kernel-isolated','filesystem not OS-isolated','memory/cpu limits not OS-enforced']}}
async function executeProcess(command,meta={}){if(!allowed(command))throw new Error('desktop adapter received a command outside the benchmark allowlist');const root=str(meta.workingDirectory);const cwd=root||fs.mkdtempSync(path.join(os.tmpdir(),'mastermind-sandbox-'));const args=command.trim().split(/\s+/);const executable=args.shift();const r=await runProcess(executable,args,{cwd,timeoutMs:meta.timeoutMs,maxOutputBytes:meta.maxOutputBytes});const verification=meta.runtimeVerification===false?{verified:false,status:'skipped',source:'runtime-probe'}:await verifyRuntime(meta);return{...r,isolationLevel:verification.verified?'process-isolated':(r.timedOut?'process-isolated-timeout':'process-unverified'),isolationBackend:'native-child-process',network:'not-kernel-isolated',filesystem:'workspace-confined-cwd',shell:false,resourceLimits:{timeoutMs:num(meta.timeoutMs,30000,1000,120000),maxOutputBytes:Number(meta.maxOutputBytes||12000),maxMemoryMb:meta.maxMemoryMb?Number(meta.maxMemoryMb):null,maxCpus:meta.maxCpus?Number(meta.maxCpus):null},killController:{active:true,trigger:r.timedOut?'timeout':null,scope:'process-tree',verified:Boolean(verification.probes?.processTreeKilled)},runtimeVerification:verification}}
module.exports={executeProcess,verifyRuntime};
