/** Universal Skill Execution Sandbox 2.0 - Desktop */
const UNIVERSAL_SKILL_EXECUTION_SANDBOX_VERSION='2.0-isolated-execution';
function usesObj(v){return v&&typeof v==='object'&&!Array.isArray(v)?v:{};}function usesStr(v){return typeof v==='string'?v:'';}function usesNum(v,d,min,max){const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):d;}function usesId(){return `sandbox-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;}function usesRedact(v){return usesStr(v).replace(/(api[_-]?key|token|secret|password|authorization|bearer)\s*[:=]\s*[^\s,;]+/gi,'$1=[REDACTED]').slice(-12000);}
function normalizeSandboxSpec(input={}){const x=usesObj(input),l=usesObj(x.limits);return{timeoutMs:usesNum(l.timeoutMs??x.timeoutMs,30000,1000,120000),maxOutputBytes:Math.floor(usesNum(l.maxOutputBytes,12000,1000,200000)),maxFiles:Math.floor(usesNum(l.maxFiles,200,1,5000)),network:'disabled',filesystem:'isolated-workspace',processIsolation:x.processIsolation==='policy-only'?'policy-only':'required',backend:x.backend==='docker'?'docker':x.backend==='policy'?'policy':'process',allowCommand:Boolean(x.allowCommand),workingDirectory:usesStr(x.workingDirectory||'sandbox'),cleanup:x.cleanup!==false,readOnlyRoot:x.readOnlyRoot!==false,dropPrivileges:x.dropPrivileges!==false};}
function sandboxCreate(input={}){const spec=normalizeSandboxSpec(input);return{id:usesId(),version:UNIVERSAL_SKILL_EXECUTION_SANDBOX_VERSION,status:'prepared',isolationLevel:spec.backend==='docker'?'container-pending':spec.backend==='process'?'process-pending':'policy-only',spec,safety:{network:'disabled',importedSourceCodeExecuted:false,arbitraryCodeAllowed:false}};}
function clamp(v,n){const s=usesRedact(v);return s.length<=n?{value:s,truncated:false}:{value:s.slice(0,n),truncated:true};}
async function sandboxExecute(input={},adapter={}){const session=sandboxCreate(input.sandbox||input);if(!session.spec.allowCommand)return{ok:false,session,status:'blocked',failure:'sandbox execution requires explicit allowCommand=true'};if(typeof adapter.execute!=='function')return{ok:false,session,status:'unavailable',failure:'no isolated execution adapter supplied'};if(session.spec.backend==='policy'&&session.spec.processIsolation!=='policy-only')return{ok:false,session,status:'blocked',failure:'policy-only backend cannot satisfy required process isolation'};session.status='running';const started=Date.now();try{const raw=await adapter.execute(input.command,{sandboxId:session.id,timeoutMs:session.spec.timeoutMs,maxOutputBytes:session.spec.maxOutputBytes,maxFiles:session.spec.maxFiles,network:'disabled',workingDirectory:session.spec.workingDirectory,filesystem:session.spec.filesystem,processIsolation:session.spec.processIsolation,backend:session.spec.backend,readOnlyRoot:session.spec.readOnlyRoot,dropPrivileges:session.spec.dropPrivileges,cleanup:session.spec.cleanup});const r=usesObj(raw),verified=['container-isolated','process-isolated'].includes(usesStr(r.isolationLevel)),level=verified?r.isolationLevel:'adapter-enforced';const out=clamp([r.stdout,r.stderr,r.output,r.result,r.message].filter(Boolean).join('\n'),session.spec.maxOutputBytes);session.status='completed';return{ok:r.success!==false,status:'completed',session:{...session,status:'completed'},evidence:{command:usesStr(input.command),exitCode:typeof r.exitCode==='number'?r.exitCode:(typeof r.code==='number'?r.code:0),elapsedMs:Date.now()-started,output:out.value,outputTruncated:out.truncated,resourceLimits:session.spec,sourceExecution:{importedSourceCodeExecuted:false,arbitraryCodeAllowed:false},isolation:{level,verified,backend:session.spec.backend,network:'disabled',filesystem:session.spec.filesystem,processIsolation:session.spec.processIsolation}}};}catch(e){session.status='failed';return{ok:false,status:'failed',session:{...session,status:'failed'},evidence:{command:usesStr(input.command),elapsedMs:Date.now()-started,error:usesRedact(e?.message||String(e)),resourceLimits:session.spec,isolation:{level:'adapter-enforced',verified:false,backend:session.spec.backend}};}finally{if(session.spec.cleanup)session.status='destroyed';}}
async function sandboxManager(action,args={},adapter={}){const a=String(action||'prepare').toLowerCase();if(a==='prepare'||a==='create')return sandboxCreate(args);if(a==='execute'||a==='run')return sandboxExecute(args,adapter);if(a==='validate')return{ok:Boolean(usesStr(args.command)),spec:normalizeSandboxSpec(args),contractVersion:UNIVERSAL_SKILL_EXECUTION_SANDBOX_VERSION,requiredIsolation:normalizeSandboxSpec(args).processIsolation};if(a==='destroy')return{ok:true,status:'destroyed',sandboxId:usesStr(args.sandboxId)};return{ok:false,error:'unknown_sandbox_action',actions:['prepare','create','execute','run','validate','destroy']};}
const UNIVERSAL_SKILL_EXECUTION_SANDBOX_ENGINE={version:UNIVERSAL_SKILL_EXECUTION_SANDBOX_VERSION,create:sandboxCreate,execute:sandboxExecute,manage:sandboxManager};
