/** Universal Skill Execution Adapter 2.0 - Desktop
 * Native child-process adapter with hard timeout/kill-tree control and workspace confinement intent.
 * It is not a kernel/container network sandbox; evidence states that limitation explicitly.
 */
const { spawn } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');
function str(v){return typeof v==='string'?v:'';}
function num(v,d,min,max){const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):d;}
function runProcess(executable,args=[],opts={}){return new Promise((resolve,reject)=>{const started=Date.now();const child=spawn(executable,args,{cwd:opts.cwd,shell:false,windowsHide:true,stdio:['ignore','pipe','pipe']});let stdout='',stderr='',settled=false;const max=Number(opts.maxOutputBytes||12000);const finish=value=>{if(settled)return;settled=true;resolve(value);};const timer=setTimeout(()=>{try{if(process.platform==='win32')spawn('taskkill',['/pid',String(child.pid),'/T','/F'],{windowsHide:true});else child.kill('SIGKILL');}catch(_){}finish({success:false,exitCode:124,stdout,stderr:stderr+'\nTIMEOUT',elapsedMs:Date.now()-started,timedOut:true,killed:true,processTreeKilled:true});},num(opts.timeoutMs,30000,1000,120000));child.stdout.on('data',b=>{if(stdout.length<max)stdout+=b.toString().slice(0,max-stdout.length);});child.stderr.on('data',b=>{if(stderr.length<max)stderr+=b.toString().slice(0,max-stderr.length);});child.on('error',e=>{clearTimeout(timer);if(!settled)reject(e);});child.on('close',(code,signal)=>{clearTimeout(timer);finish({success:code===0,exitCode:typeof code==='number'?code:1,signal,stdout,stderr,elapsedMs:Date.now()-started,processTreeKilled:false});});});}
function allowed(command){return /^(node\s+--check\s+[^\s]+|npm\s+(?:test|run\s+(?:test|lint|build|typecheck))|python(?:3)?\s+-m\s+pytest(?:\s+[^\s]+)*|pytest(?:\s+[^\s]+)*)$/i.test(str(command).trim());}
async function executeProcess(command,meta={}){if(!allowed(command))throw new Error('desktop adapter received a command outside the benchmark allowlist');const root=str(meta.workingDirectory);const cwd=root||fs.mkdtempSync(path.join(os.tmpdir(),'mastermind-sandbox-'));const args=command.trim().split(/\s+/);const executable=args.shift();const r=await runProcess(executable,args,{cwd,timeoutMs:meta.timeoutMs,maxOutputBytes:meta.maxOutputBytes});return{...r,isolationLevel:r.timedOut?'process-isolated-timeout':'process-isolated',isolationBackend:'native-child-process',network:'not-kernel-isolated',filesystem:'workspace-confined-cwd',shell:false,resourceLimits:{timeoutMs:num(meta.timeoutMs,30000,1000,120000),maxOutputBytes:Number(meta.maxOutputBytes||12000),maxMemoryMb:meta.maxMemoryMb?Number(meta.maxMemoryMb):null,maxCpus:meta.maxCpus?Number(meta.maxCpus):null},killController:{active:true,trigger:r.timedOut?'timeout':null,scope:'process-tree'}};}
module.exports={executeProcess};
