const fs=require('fs');

const helper=String.raw`
const EVIDENCE_OPERATING_LOOP_VERSION='2.0-evidence-driven';
function evStatus(v){if(v==null)return'unknown';if(typeof v==='boolean')return v?'pass':'fail';const s=String(v).toLowerCase();if(/pass|success|ok|healthy|verified|complete|accepted|resolved/.test(s))return'pass';if(/fail|error|blocked|unhealthy|rejected|rollback/.test(s))return'fail';return'unknown';}
function evArr(v){return Array.isArray(v)?v:[];}
function evSummary(s){if(!s||typeof s!=='object')return{available:false,fileCount:0,componentCount:0};const f=Array.isArray(s.files)?s.files:(s.fileMap&&typeof s.fileMap==='object'?Object.keys(s.fileMap):[]);const c=Array.isArray(s.components)?s.components:(s.architecture&&Array.isArray(s.architecture.components)?s.architecture.components:[]);return{available:true,fileCount:f.length,componentCount:c.length,framework:s.framework||s.language||s.architecture?.framework||null,platform:s.platform||s.architecture?.platform||null};}
function evFp(s){try{const n=typeof architectNormalizeSnapshot==='function'?architectNormalizeSnapshot(s||{}):(s||{});const j=JSON.stringify(n);let h=2166136261;for(let i=0;i<j.length;i++){h^=j.charCodeAt(i);h+=(h<<1)+(h<<4)+(h<<7)+(h<<8)+(h<<24);}return(h>>>0).toString(16);}catch(_){return'';}}
async function evDiscover(env,root){try{if(env==='GitHub Cloud'&&typeof performCloudArchitectureDiscovery==='function')return await Promise.resolve(performCloudArchitectureDiscovery(root));if(typeof performArchitectureDiscovery==='function')return await Promise.resolve(performArchitectureDiscovery(root));return null;}catch(e){return{error:String(e?.message||e)};}}
function evVerify(r){const v=r?.verification||r?.closedLoop?.verification||{};return evStatus(v?.status??v?.overall?.status??v?.result??r?.closedLoop?.status);}
function evCriterion(id,ok,required,reason,evidence){return{id,required:required!==false,status:ok===true?'pass':ok===false?'fail':'unknown',reason:reason||'',evidence:evidence||null};}
function evEvaluate(o,r,b,p){const verify=o.verify!==false,impl=!!r?.implementation?.changed,vs=evVerify(r),bf=evFp(b),pf=evFp(p),archChanged=!!(bf&&pf&&bf!==pf);const custom=evArr(o.acceptanceCriteria);const criteria=custom.length?custom.map((c,i)=>{c=typeof c==='string'?{id:`custom_${i+1}`,type:c,required:true}:c;if(c.type==='implementation_changed')return evCriterion(c.id,impl,c.required,impl?'Implementation changed.':'No implementation change proven.');if(c.type==='architecture_changed')return evCriterion(c.id,archChanged,c.required,archChanged?'Pre/post architecture differs.':'No architecture difference proven.',{bf,pf});if(c.type==='verification_pass')return evCriterion(c.id,vs==='pass',c.required,`Verification: ${vs}.`);if(c.type==='post_discovery')return evCriterion(c.id,!!p&&!p.error,c.required,p&&!p.error?'Post discovery completed.':'Post discovery failed.',evSummary(p));return evCriterion(c.id,null,c.required,`Unsupported criterion: ${c.type}.`);}):[evCriterion('objective_defined',!!String(o.objective||'').trim(),true,'Mission objective is explicit.'),evCriterion('architecture_plan',!!r?.plan,true,r?.plan?'Architect plan returned.':'No architect plan returned.'),evCriterion('verification_evidence',!verify||vs==='pass'||vs==='unknown',true,verify?`Verification: ${vs}.`:'Verification disabled.'),evCriterion('post_discovery',!!p&&!p.error,true,p&&!p.error?'Post discovery completed.':'Post discovery failed.',evSummary(p)),evCriterion('no_unresolved_failure',evStatus(r?.status)!=='fail',true,`Loop status: ${evStatus(r?.status)}.`)];const req=criteria.filter(x=>x.required),fail=req.filter(x=>x.status==='fail'),unknown=req.filter(x=>x.status==='unknown');let verdict='partial';if(evStatus(r?.status)==='fail'||vs==='fail'||fail.length)verdict='failed';else if(!unknown.length&&(!verify||vs==='pass'))verdict='accepted';let score=(b&&!b.error?15:0)+(r?.plan?20:0)+(impl?15:0)+(verify&&vs==='pass'?25:(verify?5:10))+(p&&!p.error?15:0)+(archChanged?10:0);score=Math.max(0,Math.min(100,score));if(verdict==='failed')score=Math.min(score,35);else if(verdict==='partial')score=Math.min(score,79);return{verdict,confidence:{score,level:score>=85?'high':score>=60?'medium':'low',reasons:[verdict==='accepted'?'All required evidence gates passed.':'',!impl?'No implementation change was proven.':'',verify&&vs!=='pass'?`Functional verification is not proven (${vs}).`:'',!p||p.error?'Post-change discovery is missing or failed.':'',unknown.length?`${unknown.length} required criterion(s) are unknown.`:''].filter(Boolean)},criteria,facts:{bf,pf,archChanged,vs,impl}};}
async function runUniversalAgentOperatingLoop(options={}){const startedAt=new Date().toISOString(),missionId=options.missionId||`mission-${Date.now().toString(36)}`,environment=options.environment||(typeof performCloudArchitectureDiscovery==='function'?'GitHub Cloud':'Windows Desktop'),root=typeof normalizePathForCloud==='function'?normalizePathForCloud(options.root||''):(options.root||''),verify=options.verify!==false;const baseline=await evDiscover(environment,root);let legacy;try{legacy=await runUniversalAgentOperatingLoopLegacy({...options,environment,root,verify});}catch(e){legacy={status:'failed',error:String(e?.message||e),implementation:{changed:false,executions:[]}};}const post=await evDiscover(environment,root),acceptance=evEvaluate(options,legacy,baseline,post),finishedAt=new Date().toISOString();return{...legacy,available:true,version:EVIDENCE_OPERATING_LOOP_VERSION,status:acceptance.verdict,success:acceptance.verdict==='accepted',mission:{missionId,objective:String(options.objective||'').trim(),environment,root,startedAt,finishedAt},acceptance,evidence:{baseline:{summary:evSummary(baseline),fingerprint:evFp(baseline)},implementation:{changed:!!legacy?.implementation?.changed,executions:evArr(legacy?.implementation?.executions).length},verification:{status:evVerify(legacy)},postDiscovery:{summary:evSummary(post),fingerprint:evFp(post)},architectureDiff:legacy?.architectureDiff||null},checkpoint:{missionId,phase:acceptance.verdict==='accepted'?'completed':acceptance.verdict==='failed'?'failed':'needs_review',finalVerdict:acceptance.verdict,confidence:acceptance.confidence},successReason:acceptance.confidence.reasons.join(' '),failureReason:acceptance.verdict==='failed'?acceptance.confidence.reasons.join(' '):null};}
`;

function endOfFunction(s,marker){const start=s.indexOf(marker);if(start<0)throw Error('Missing '+marker);const open=s.indexOf('{',start);let d=0,q=null,e=false,line=false,block=false,end=-1;for(let i=open;i<s.length;i++){const c=s[i],n=s[i+1];if(line){if(c==='\n')line=false;continue;}if(block){if(c==='*'&&n==='/'){block=false;i++;}continue;}if(q){if(e){e=false;continue;}if(c==='\\'){e=true;continue;}if(c===q)q=null;continue;}if(c==='/'&&n==='/'){line=true;i++;continue;}if(c==='/'&&n==='*'){block=true;i++;continue;}if(c==='\''||c==='"'||c==='`'){q=c;continue;}if(c==='{')d++;else if(c==='}'&&--d===0){end=i+1;break;}}if(end<0)throw Error('Unbalanced '+marker);return{start,end};}
for(const file of ['my_AI/ai_engine_core.js','Mastermind_Desktop/core.js']){let s=fs.readFileSync(file,'utf8');if(s.includes("const EVIDENCE_OPERATING_LOOP_VERSION='2.0-evidence-driven';"))continue;const old=endOfFunction(s,'async function runUniversalAgentOperatingLoop');const open=s.indexOf('{',old.start);const prefix=s.slice(old.start,open).replace('async function runUniversalAgentOperatingLoop','async function runUniversalAgentOperatingLoopLegacy');s=s.slice(0,old.start)+prefix+s.slice(open);const renamed=endOfFunction(s,'async function runUniversalAgentOperatingLoopLegacy');s=s.slice(0,renamed.end)+'\n\n'+helper+'\n'+s.slice(renamed.end);fs.writeFileSync(file,s);console.log('patched',file);}
NODE
