/**
 * Universal Skill Synthesis Engine 1.0
 * Converts external/local knowledge sources into validated declarative Skills.
 * No arbitrary source code execution; synthesis is evidence/provenance driven.
 */
const UNIVERSAL_SKILL_SYNTHESIS_VERSION='1.0-synthesis';
function usseArray(v){return Array.isArray(v)?v:[];}function usseObj(v){return v&&typeof v==='object'&&!Array.isArray(v)?v:{};}function usseStr(v){return typeof v==='string'?v:'';}
function usseClean(s){return usseStr(s).replace(/\r/g,'').replace(/\s+/g,' ').trim();}
function usseRelevant(path=''){return /\.(md|markdown|txt|json|ya?ml|js|mjs|cjs|ts|tsx|py|java|kt|go|rs|rb|php|cs|cpp|h|pdf)$/i.test(path)&&!/(node_modules|dist|build|coverage|\.git)/i.test(path);}
function usseExtractUnits(sources=[],limits={}){const maxFiles=Number(limits.maxFiles||80),maxChars=Number(limits.maxCharsPerFile||120000);const units=[];for(const src of usseArray(sources).slice(0,maxFiles)){const path=usseStr(src.path),text=usseStr(src.text).slice(0,maxChars);if(!path||!text||!usseRelevant(path))continue;const headings=[...text.matchAll(/^\s{0,3}(#{1,6})\s+(.+)$/gm)].map(m=>usseClean(m[2])).filter(Boolean).slice(0,40);const rules=[...text.matchAll(/(?:must|should|shall|required|never|always|avoid|do not|لا يجب|يجب|ينبغي|تجنب)\b[^\n.;]{0,240}/gi)].map(m=>usseClean(m[0])).slice(0,40);const codeSignals=[...text.matchAll(/\b(?:function|class|interface|workflow|pipeline|tool|command|script|endpoint|route|handler|validator|parser)\b[^\n]{0,180}/gi)].map(m=>usseClean(m[0])).slice(0,40);units.push({path,headings,rules,codeSignals,excerpt:text.slice(0,Math.min(text.length,18000)),characters:text.length});}return units;}
function usseSynthesizeSkill(input={},options={}){const units=usseExtractUnits(input.sources||[],options);const name=usseStr(input.name||input.topic||'Synthesized Expert Skill');const id=usseStr(input.id||('skill.'+name.toLowerCase().replace(/[^a-z0-9]+/g,'.').replace(/^\.|\.$/g,'')))||('skill.'+Date.now());const domain=usseStr(input.domain||'general');const headings=[...new Set(units.flatMap(x=>x.headings))].slice(0,40);const rules=[...new Set(units.flatMap(x=>x.rules))].slice(0,50);const signals=[...new Set(units.flatMap(x=>x.codeSignals))].slice(0,50);const instructions=[`Use the synthesized knowledge from ${units.length} analyzed source files as task context.`,`Prefer evidence from cited source paths over unsupported assumptions.`,...rules.slice(0,20)];const workflow=[{id:'source-analysis',action:'analyze_sources',purpose:'Review synthesized source units before acting.',tool:'discovery_scan',expectedEvidence:['source inventory','relevant knowledge units'],stopConditions:['source set is empty']}];if(headings.length)workflow.push({id:'expert-procedure',action:'apply_domain_knowledge',purpose:'Apply extracted domain procedures and concepts.',tool:'skill_context',inputs:{topics:headings.slice(0,15)},expectedEvidence:['task-specific evidence'],stopConditions:['evidence conflicts with source']});return{skill:{id,name,version:'0.1.0',description:usseStr(input.description||`Synthesized expert skill derived from ${units.length} source files.`),domain,triggers:usseArray(input.triggers).length?input.triggers:headings.slice(0,12),tags:[domain,'synthesized','evidence-driven'],prerequisites:[],instructions,workflow,capabilities:signals.slice(0,15).map((x,i)=>({id:`cap.${i+1}`,name:x.slice(0,100),description:'Capability inferred from source evidence.',tools:['discovery_scan','read_file'],safe:true})),constraints:['Do not treat inferred knowledge as fact without source evidence.','Do not execute imported source code as part of skill synthesis.'],validation:{required:['skill schema validation','provenance recorded'],commands:[],evidence:['source paths','source excerpts']},outputs:['validated skill definition','source provenance','knowledge units'],safety:{allowNetwork:false,allowWrites:false,allowTerminal:false,allowSecrets:false,arbitraryCode:false},provenance:{sourceType:usseStr(input.sourceType||'synthesized'),repository:usseStr(input.repository),path:usseStr(input.path),ref:usseStr(input.ref||'main')},status:'draft'},evidence:{sources:units.map(u=>({path:u.path,characters:u.characters,headings:u.headings,rules:u.rules})),unitCount:units.length,topic:name,domain},limitations:units.length?'Synthesis is source-structure aware; semantic claims should be validated by the model and runtime evidence.':'No relevant sources were available for synthesis.'};}
function usseValidateSynthesis(result={}){const skill=usseObj(result.skill),errors=[];if(!skill.id)errors.push('missing skill id');if(!skill.name)errors.push('missing skill name');if(!skill.description)errors.push('missing description');if(!usseArray(skill.instructions).length&&!usseArray(skill.workflow).length)errors.push('missing procedure');if(skill.safety?.arbitraryCode)errors.push('arbitrary code is forbidden');if(!usseArray(result.evidence?.sources).length)errors.push('missing provenance evidence');return{valid:!errors.length,errors,result};}
function universalSkillSynthesisManager(action,args={},adapter={}){const a=String(action||'').toLowerCase();if(a==='synthesize'||a==='build'){return usseSynthesizeSkill(args,args.options||{});}if(a==='validate'){return usseValidateSynthesis(args.result||args.synthesis||{});}if(a==='extract'){return{ok:true,version:UNIVERSAL_SKILL_SYNTHESIS_VERSION,units:usseExtractUnits(args.sources||[],args.options||{})};}if(a==='import_github_sources'){if(typeof adapter.fetchSources!=='function')return{ok:false,error:'github_source_adapter_unavailable'};return Promise.resolve(adapter.fetchSources(args)).then(sources=>usseSynthesizeSkill({...args,sources,sourceType:'github'},args.options||{}));}if(a==='import_local_sources'){if(typeof adapter.readSources!=='function')return{ok:false,error:'local_source_adapter_unavailable'};return Promise.resolve(adapter.readSources(args)).then(sources=>usseSynthesizeSkill({...args,sources,sourceType:'local'},args.options||{}));}return{ok:false,error:'unknown_synthesis_action',actions:['synthesize','extract','validate','import_github_sources','import_local_sources']};}
const UNIVERSAL_SKILL_SYNTHESIS_ENGINE={version:UNIVERSAL_SKILL_SYNTHESIS_VERSION,synthesize:usseSynthesizeSkill,extract:usseExtractUnits,validate:usseValidateSynthesis,manage:universalSkillSynthesisManager};
