/**
 * Universal Skill Deep Understanding Engine 1.0
 * Builds a structured semantic model from synthesized source units before a Skill is activated.
 * No arbitrary source-code execution.
 */
const UNIVERSAL_SKILL_DEEP_UNDERSTANDING_VERSION='1.0-deep-understanding';
function usduArray(v){return Array.isArray(v)?v:[];}function usduObj(v){return v&&typeof v==='object'&&!Array.isArray(v)?v:{};}function usduStr(v){return typeof v==='string'?v:'';}function usduClean(v){return usduStr(v).replace(/\r/g,'').replace(/\s+/g,' ').trim();}
function usduTokens(text=''){return [...new Set(usduStr(text).toLowerCase().match(/[a-z0-9_\u0600-\u06ff-]{3,}/gi)||[])];}
function usduConcepts(units=[]){const counts=new Map();for(const u of usduArray(units)){const text=[u.path,...usduArray(u.headings),...usduArray(u.rules),...usduArray(u.codeSignals),u.excerpt||''].join(' ');for(const t of usduTokens(text)){if(/^(the|and|for|with|from|that|this|must|should|required|function|class|const|return|async|await|true|false)$/.test(t))continue;counts.set(t,(counts.get(t)||0)+1);}}return[...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,120).map(([term,count])=>({term,count}));}
function usduRelations(units=[]){const rel=[];const seen=new Set();for(const a of usduArray(units)){const aText=[...usduArray(a.headings),...usduArray(a.rules),...usduArray(a.codeSignals)].join(' ').toLowerCase();for(const b of usduArray(units)){if(a.path===b.path)continue;const overlap=usduTokens(aText).filter(t=>usduTokens([b.path,...usduArray(b.headings),...usduArray(b.rules)].join(' ')).includes(t));if(overlap.length<3)continue;const key=[a.path,b.path].sort().join('|');if(seen.has(key))continue;seen.add(key);rel.push({from:a.path,to:b.path,sharedConcepts:overlap.slice(0,12)});}}return rel.slice(0,250);}
function usduConflicts(units=[]){const positive=[],negative=[];for(const u of usduArray(units)){for(const r of usduArray(u.rules)){if(/\b(always|must|required|يجب|ينبغي)\b/i.test(r))positive.push({path:u.path,rule:r});if(/\b(never|must not|required not|do not|تجنب|لا يجب)\b/i.test(r))negative.push({path:u.path,rule:r});}}const conflicts=[];for(const p of positive){const pk=usduTokens(p.rule).filter(x=>x.length>4);for(const n of negative){const nk=usduTokens(n.rule).filter(x=>x.length>4);const shared=pk.filter(x=>nk.includes(x));if(shared.length>=2)conflicts.push({positive:p,negative:n,sharedTerms:shared});}}return conflicts.slice(0,100);}
function usduProcedures(units=[]){const procedures=[];for(const u of usduArray(units)){const candidates=[...usduArray(u.rules),...usduArray(u.codeSignals)].filter(x=>/\b(then|after|before|first|next|finally|if|when|must|should|يجب|بعد|قبل|أولاً|ثم|إذا|عند)\b/i.test(x));for(const c of candidates.slice(0,20))procedures.push({source:u.path,statement:usduClean(c),kind:/\b(if|when|إذا|عند)\b/i.test(c)?'conditional':'directive'});}return procedures.slice(0,180);}
function usduEvidenceMap(units=[]){return usduArray(units).map(u=>({source:u.path,headings:usduArray(u.headings),rules:usduArray(u.rules).slice(0,25),codeSignals:usduArray(u.codeSignals).slice(0,25),excerpt:u.excerpt?String(u.excerpt).slice(0,4000):''}));}
function usduBuildModel(input={}){const units=usduArray(input.units||input.sources||[]);const concepts=usduConcepts(units),relations=usduRelations(units),conflicts=usduConflicts(units),procedures=usduProcedures(units),evidence=usduEvidenceMap(units);const domain=usduStr(input.domain||'general'),topic=usduStr(input.topic||input.name||'Expert Domain');const confidence=units.length?Math.min(0.95,0.35+Math.min(0.45,units.length*0.02)+Math.min(0.15,concepts.length*0.001)):0;return{version:UNIVERSAL_SKILL_DEEP_UNDERSTANDING_VERSION,domain,topic,sourceCount:units.length,concepts,relations,procedures,conflicts,evidence,confidence,limitations:conflicts.length?'Source rules contain potential conflicts; resolve with model reasoning and explicit evidence before activation.':'Semantic model is structure/evidence aware; factual certainty still depends on source quality and verification.'};}
function usduSynthesize(input={}){const model=usduBuildModel(input);const topConcepts=model.concepts.slice(0,30).map(x=>x.term);const instructions=[`Build task decisions from the Deep Understanding model for ${model.topic}.`,`Prefer source-backed procedures and cite provenance when making expert claims.`,`When source rules conflict, do not silently choose; surface the conflict and seek evidence.`,...model.procedures.slice(0,25).map(p=>p.statement)];const workflow=[{id:'understand',action:'load_semantic_model',purpose:'Use concepts, relations, procedures and conflicts before applying the Skill.',tool:'skill_deep_context',expectedEvidence:['semantic model','source provenance'],stopConditions:['no source evidence']}];if(model.conflicts.length)workflow.push({id:'conflict-resolution',action:'resolve_source_conflicts',purpose:'Resolve contradictory directives before execution.',tool:'evidence_engine',expectedEvidence:['conflict resolution evidence'],stopConditions:['unresolved high-risk conflict']});workflow.push({id:'apply',action:'apply_expert_procedure',purpose:'Apply domain-specific procedure using the semantic model.',tool:'skill_context',inputs:{concepts:topConcepts},expectedEvidence:['task outcome evidence'],stopConditions:['evidence contradicts source']});return{skill:{id:usduStr(input.id||`skill.deep.${String(input.topic||'expert').toLowerCase().replace(/[^a-z0-9]+/g,'.')}`),name:usduStr(input.name||`Deep Expert Skill: ${model.topic}`),version:'0.2.0',description:usduStr(input.description||`Deep-understanding expert Skill for ${model.topic} derived from ${model.sourceCount} source units.`),domain:model.domain,triggers:topConcepts.slice(0,15),tags:[model.domain,'deep-understanding','evidence-driven'],instructions,workflow,capabilities:topConcepts.slice(0,20).map((x,i)=>({id:`deep.cap.${i+1}`,name:x,description:'Concept identified in source evidence.',tools:['skill_deep_context','read_file'],safe:true})),constraints:['Preserve source provenance.','Do not silently resolve conflicting source rules.','Do not execute imported source code.'],validation:{required:['semantic model generated','provenance available','conflicts reviewed'],commands:[],evidence:['concept graph','procedure map','conflict report','source evidence']},outputs:['deep skill definition','semantic model','conflict report','evidence map'],safety:{allowNetwork:false,allowWrites:false,allowTerminal:false,allowSecrets:false,arbitraryCode:false},provenance:{sourceType:usduStr(input.sourceType||'deep-synthesized'),repository:usduStr(input.repository),path:usduStr(input.path),ref:usduStr(input.ref||'main')},status:'draft'},understanding:model};}
function usduValidate(result={}){const model=usduObj(result.understanding),skill=usduObj(result.skill),errors=[];if(!model.sourceCount)errors.push('no source units');if(!skill.id)errors.push('missing skill id');if(!skill.workflow?.length)errors.push('missing deep workflow');if(!skill.validation?.evidence?.length)errors.push('missing evidence requirements');return{valid:!errors.length,errors,confidence:model.confidence||0,result};}
function universalSkillDeepUnderstandingManager(action,args={},adapter={}){const a=String(action||'').toLowerCase();if(a==='understand'||a==='analyze')return usduBuildModel(args);if(a==='synthesize'||a==='build'){const result=usduSynthesize(args);return{...result,validation:usduValidate(result)};}if(a==='validate')return usduValidate(args.result||args.understanding||{});if(a==='from_synthesis'){const sourceResult=args.synthesis||{};return usduSynthesize({...args,units:sourceResult.units||sourceResult.evidence?.sources||[],sourceType:'synthesis'});}if(a==='import_github_sources'&&typeof adapter.fetchSources==='function')return Promise.resolve(adapter.fetchSources(args)).then(sources=>usduSynthesize({...args,units:sources,sourceType:'github-deep'}));if(a==='import_local_sources'&&typeof adapter.readSources==='function')return Promise.resolve(adapter.readSources(args)).then(sources=>usduSynthesize({...args,units:sources,sourceType:'local-deep'}));return{ok:false,error:'unknown_deep_understanding_action',actions:['understand','analyze','synthesize','build','validate','from_synthesis','import_github_sources','import_local_sources']};}
const UNIVERSAL_SKILL_DEEP_UNDERSTANDING_ENGINE={version:UNIVERSAL_SKILL_DEEP_UNDERSTANDING_VERSION,understand:usduBuildModel,synthesize:usduSynthesize,validate:usduValidate,manage:universalSkillDeepUnderstandingManager};
