/** Universal Skill Execution Sandbox 1.0 - Cloud
 * Policy/execution envelope. OS isolation is supplied by the execution adapter.
 */
const UNIVERSAL_SKILL_EXECUTION_SANDBOX_VERSION='1.0-sandbox-contract';
function usesObj(v){return v&&typeof v==='object'&&!Array.isArray(v)?v:{};}
function usesStr(v){return typeof v==='string'?v:'';}
function usesNum(v,d,min,max){const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):d;}
function usesId(){return `sandbox-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;}
function usesRedact(v){return usesStr(v).replace(/(api[_-]?key|token|secret|password|authorization|bearer)\s*[:=]\s*[^\s,;]+/gi,'$1=[REDACTED]').slice(-12000);}
function normalizeSandboxSpec(input={}){const x=usesObj(input),limits=usesObj(x.limits);return{timeoutMs:usesNum(limits.timeoutMs??x.timeoutMs,30000,1000,120000),maxOutputBytes:Math.floor(usesNum(limits.maxOutputBytes,12000,1000,200000)),maxFiles:Math.floor(usesNum(limits.maxFiles,200,1,5000)),network: x.network==='enabled'?'enabled':'disabled',filesystem: x.filesystem==='workspace'?'workspace':'isolated-workspace',process: x.process==='native'?'native-adapter':'adapter-isolated',allowCommand:Boolean(x.allowCommand),workingDirectory:usesStr(x.workingDirectory||'sandbox'),cleanup:x.cleanup!==false};}
function sandboxCreate(input={}){const spec=normalizeSandboxSpec(input);return{id:usesId(),version:UNIVERSAL_SKILL_EXECUTION_SANDBOX_VERSION,status:'prepared',isolationLevel:'adapter-enforced',spec,safety:{networkDefault:'disabled',importedSourceCodeExecuted:false,arbitraryCodeAllowed:false}};}
function sandboxClampOutput(value,maxBytes){const s=usesRedact(value);if(s.length<=maxBytes)return{value:s,truncated:false};return{value:s.slice(0,maxBytes),truncated:true};}
async function sandboxExecute(input={},adapter={}){const session=sandboxCreate(input.sandbox||input);if(!session.spec.allowCommand)return{ok:false,session,status:'blocked',failure:'sandbox execution requires explicit allowCommand=true'};if(typeof adapter.execute!=='function')return{ok:false,session,status:'unavailable',failure:'sandbox execution adapter unavailable'};session.status='running';const started=Date.now();try{const raw=await adapter.execute(input.command,{sandboxId:session.id,timeoutMs:session.spec.timeoutMs,maxOutputBytes:session.spec.maxOutputBytes,maxFiles:session.spec.maxFiles,network:session.spec.network,workingDirectory:session.spec.workingDirectory,filesystem:session.spec.filesystem,process:session.spec.process});const r=usesObj(raw),out=sandboxClampOutput([r.stdout,r.stderr,r.output,r.result,r.message].filter(Boolean).join('\n'),session.spec.maxOutputBytes);session.status='completed';return{ok:r.success!==false,status:'completed',session:{...session,status:'completed'},evidence:{command:usesStr(input.command),exitCode:typeof r.exitCode==='number'?r.exitCode:(typeof r.code==='number'?r.code:0),elapsedMs:Date.now()-started,output:out.value,outputTruncated:out.truncated,resourceLimits:session.spec,sourceExecution:{importedSourceCodeExecuted:false,arbitraryCodeAllowed:false},isolation:{level:'adapter-enforced',network:session.spec.network,filesystem:session.spec.filesystem,process:session.spec.process}}};}catch(e){session.status='failed';return{ok:false,status:'failed',session:{...session,status:'failed'},evidence:{command:usesStr(input.command),elapsedMs:Date.now()-started,error:usesRedact(e?.message||String(e)),resourceLimits:session.spec,isolation:{level:'adapter-enforced'}}};}finally{if(session.spec.cleanup)session.status='destroyed';}}
async function sandboxManager(action,args={},adapter={}){const a=String(action||'prepare').toLowerCase();if(a==='prepare'||a==='create')return sandboxCreate(args);if(a==='execute'||a==='run')return sandboxExecute(args,adapter);if(a==='validate')return{ok:Boolean(usesStr(args.command)),spec:normalizeSandboxSpec(args),contractVersion:UNIVERSAL_SKILL_EXECUTION_SANDBOX_VERSION};if(a==='destroy')return{ok:true,status:'destroyed',sandboxId:usesStr(args.sandboxId)};return{ok:false,error:'unknown_sandbox_action',actions:['prepare','create','execute','run','validate','destroy']};}
const UNIVERSAL_SKILL_EXECUTION_SANDBOX_ENGINE={version:UNIVERSAL_SKILL_EXECUTION_SANDBOX_VERSION,create:sandboxCreate,execute:sandboxExecute,manage:sandboxManager};
