/** Universal Skill Execution Adapter 2.0 - Cloud
 * Docker-backed execution with hard resource limits, network isolation, and kill control.
 */
const { spawn } = require('child_process');
function str(v){return typeof v==='string'?v:'';}
function num(v,d,min,max){const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):d;}
function safeName(v){return str(v).replace(/[^a-zA-Z0-9_.-]/g,'_').slice(0,70)||'sandbox';}
function runProcess(command,args=[],opts={}){return new Promise((resolve,reject)=>{const started=Date.now();const child=spawn(command,args,{cwd:opts.cwd,shell:false,windowsHide:true,stdio:['ignore','pipe','pipe'],env:{PATH:process.env.PATH||''}});let stdout='',stderr='';const max=Number(opts.maxOutputBytes||12000);let settled=false;const finish=value=>{if(settled)return;settled=true;resolve(value);};const timer=setTimeout(()=>{try{child.kill('SIGKILL');}catch(_){}finish({success:false,exitCode:124,stdout,stderr:stderr+'\nTIMEOUT',elapsedMs:Date.now()-started,timedOut:true,killed:true});},num(opts.timeoutMs,30000,1000,120000));child.stdout.on('data',b=>{if(stdout.length<max)stdout+=b.toString().slice(0,max-stdout.length);});child.stderr.on('data',b=>{if(stderr.length<max)stderr+=b.toString().slice(0,max-stderr.length);});child.on('error',e=>{clearTimeout(timer);if(!settled)reject(e);});child.on('close',(code,signal)=>{clearTimeout(timer);finish({success:code===0,exitCode:typeof code==='number'?code:1,signal,stdout,stderr,elapsedMs:Date.now()-started});});});}
async function executeDocker(command,meta={}){const id=safeName(meta.sandboxId||`sb-${Date.now()}`);const image=safeName(meta.image||'node:20-alpine');const work=str(meta.workingDirectory||process.cwd());const writable=meta.filesystem==='workspace';const memory=`${Math.floor(num(meta.maxMemoryMb,256,64,2048))}m`;const cpus=String(num(meta.maxCpus,1,0.25,4));const pids=String(Math.floor(num(meta.maxProcesses,64,16,256)));const args=['run','--rm','--name',id,'--network','none','--read-only','--cap-drop','ALL','--security-opt','no-new-privileges','--pids-limit',pids,'--memory',memory,'--cpus',cpus,'--tmpfs','/tmp:rw,nosuid,nodev,noexec,size=64m','-v',`${work}:/workspace:${writable?'rw':'ro'}`,'-w','/workspace',image,'node','-e',`const cp=require('child_process');const c=${JSON.stringify(command)};cp.execFileSync('/bin/sh',['-c',c],{stdio:'inherit'});`];const started=Date.now();const r=await runProcess('docker',args,meta);if(r.timedOut){try{await runProcess('docker',['rm','-f',id],{timeoutMs:5000,maxOutputBytes:2000});}catch(_){} }return{...r,isolationLevel:r.timedOut?'container-isolated-timeout':'container-isolated',isolationBackend:'docker',network:'none-enforced',filesystem:writable?'workspace-readwrite':'workspace-readonly',readOnlyRoot:true,capDropAll:true,noNewPrivileges:true,pidsLimit:Number(pids),memoryMb:Number(memory.replace('m','')),cpus:Number(cpus),killController:{active:true,trigger:r.timedOut?'timeout':null,scope:'container'}};}
module.exports={executeDocker};
