/** Universal API Contract & Integration Testing Engine 1.0 */
const UNIVERSAL_API_TESTING_VERSION='1.0-contract-integration';
const apiArray=v=>Array.isArray(v)?v:[];
const apiObj=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};
const apiStr=v=>typeof v==='string'?v:'';
function apiRedact(v){let s=typeof v==='string'?v:JSON.stringify(v??'');return s.replace(/(api[_-]?key|token|secret|password|authorization|bearer)\s*[:=]\s*([^\s,;]+)/gi,'$1=[REDACTED]').replace(/(sk-[A-Za-z0-9_-]{10,})/g,'[REDACTED_KEY]');}
function apiJoin(base,path){return `${String(base||'').replace(/\/$/,'')}/${String(path||'').replace(/^\//,'')}`.replace(/([^:]\/)\/+/g,'$1');}
function apiSample(schema={},name='value'){schema=apiObj(schema);if(schema.example!==undefined)return schema.example;if(schema.default!==undefined)return schema.default;if(apiArray(schema.enum).length)return schema.enum[0];if(schema.oneOf)return apiSample(schema.oneOf[0],name);if(schema.anyOf)return apiSample(schema.anyOf[0],name);if(schema.type==='object'||schema.properties){const o={};for(const [k,v] of Object.entries(apiObj(schema.properties)))o[k]=apiSample(v,k);return o;}if(schema.type==='array')return[apiSample(schema.items||{},name)];if(schema.type==='integer'||schema.type==='number')return 1;if(schema.type==='boolean')return true;return name==='email'?'test@example.com':'test';}
function apiResolveSchema(root,s){if(typeof s==='string'&&s.startsWith('#/')){let x=root;for(const p of s.slice(2).split('/'))x=x?.[p];return x||{};}return apiObj(s);}
function apiYamlScalar(v){v=String(v||'').trim();if(v==='true')return true;if(v==='false')return false;if(v==='null'||v==='~')return null;if(/^[-+]?\d+(\.\d+)?$/.test(v))return Number(v);if((v.startsWith('"')&&v.endsWith('"'))||(v.startsWith("'")&&v.endsWith("'")))return v.slice(1,-1);if(v.startsWith('[')&&v.endsWith(']')){try{return JSON.parse(v.replace(/'/g,'"'));}catch{return v;}}return v;}
function apiYamlToJson(text){const lines=String(text||'').split(/\r?\n/).filter(l=>l.trim()&&!/^\s*#/.test(l));const root={};const stack=[{indent:-1,obj:root}];for(const raw of lines){const indent=(raw.match(/^\s*/)||[''])[0].length;const line=raw.trim();if(line==='---')continue;while(stack.length>1&&indent<=stack[stack.length-1].indent)stack.pop();let m=line.match(/^([^:#][^:]*):\s*(.*)$/);if(m){const key=m[1].trim(),val=m[2].trim(),parent=stack[stack.length-1].obj;if(val){parent[key]=apiYamlScalar(val);}else{parent[key]={};stack.push({indent,obj:parent[key]});continue;}}else if(line.startsWith('- ')){const parent=stack[stack.length-1].obj;if(!Array.isArray(parent.__items))parent.__items=[];parent.__items.push(apiYamlScalar(line.slice(2)));}}return root;}
function apiExtractOpenApi(doc){doc=apiObj(doc);const paths=apiObj(doc.paths),out=[];for(const [path,itemRaw] of Object.entries(paths)){const item=apiObj(itemRaw);for(const method of ['get','post','put','patch','delete','head','options']){if(!item[method])continue;const op=apiObj(item[method]),params=[...apiArray(item.parameters),...apiArray(itemRaw.parameters)];const req=apiObj(op.requestBody);const content=apiObj(req.content);const json=content['application/json']||content['application/*+json'];const statuses=Object.keys(apiObj(op.responses));const expected=Number(statuses.find(s=>/^2\d\d$/.test(s))||200);out.push({source:'openapi',method:method.toUpperCase(),path,operationId:apiStr(op.operationId)||null,summary:apiStr(op.summary)||null,parameters:params,requestSchema:json?.schema||null,expectedStatus:expected,expectedStatuses:statuses.filter(s=>/^\d{3}$/.test(s)).map(Number),responses:op.responses||{},security:op.security??doc.security??null});}}return out;}
function apiExtractRoutes(source,sourcePath){const out=[];const r=/\b(?:app|router|server|fastify)\.(get|post|put|patch|delete|head|options)\s*\(\s*[`'\"]([^`'\"]+)[`'\"]/gi;let m;while((m=r.exec(source)))out.push({source:'route-scan',sourcePath,method:m[1].toUpperCase(),path:m[2],expectedStatus:2});return out;}
async function apiDiscover(options={}){const execute=options.execute;if(typeof execute!=='function')return{available:false,error:'No command executor supplied.'};const root=String(options.root||'.');const script=`const fs=require('fs'),path=require('path');const root=${JSON.stringify(root)};const skip=new Set(['node_modules','.git','.next','dist','build','coverage']);const specs=[];const routes=[];function walk(d){let es=[];try{es=fs.readdirSync(d,{withFileTypes:true});}catch{return;}for(const e of es){if(skip.has(e.name))continue;const p=path.join(d,e.name);if(e.isDirectory()){walk(p);continue;}const rel=path.relative(root,p).replace(/\\/g,'/');if(/^(openapi|swagger)(\\.(json|ya?ml))$/i.test(e.name)||/api\\.(json|ya?ml)$/i.test(e.name)){try{specs.push({path:rel,text:fs.readFileSync(p,'utf8').slice(0,1000000)});}catch{}}if(/\\.(js|mjs|cjs|ts|tsx)$/.test(e.name)){try{const t=fs.readFileSync(p,'utf8');if(/\\b(app|router|server|fastify)\\.(get|post|put|patch|delete|head|options)\\s*\\(/.test(t))routes.push({path:rel,text:t.slice(0,300000)});}catch{}}}}walk(root);process.stdout.write(JSON.stringify({specs,routes}));`;const ev=await execute(`node -e ${JSON.stringify(script)}`,{phase:'api-discovery',timeoutMs:options.timeoutMs||120000});let raw=ev?.stdout||ev?.output||ev?.result||'';let data;try{data=JSON.parse(String(raw));}catch{return{available:false,error:'API discovery output was not valid JSON.',evidence:apiRedact(raw)}}const contracts=[];for(const s of apiArray(data.specs)){let doc;try{doc=JSON.parse(s.text);}catch{doc=apiYamlToJson(s.text);}contracts.push(...apiExtractOpenApi(doc).map(c=>({...c,sourcePath:s.path})));}for(const r of apiArray(data.routes))contracts.push(...apiExtractRoutes(r.text,r.path));const uniq=[];const seen=new Set();for(const c of contracts){const k=`${c.method} ${c.path}`;if(!seen.has(k)){seen.add(k);uniq.push(c);}}return{available:true,contracts:uniq,sources:{openapi:data.specs.map(x=>x.path),routeFiles:data.routes.map(x=>x.path)},summary:{endpoints:uniq.length,openapiEndpoints:uniq.filter(x=>x.source==='openapi').length,routeScannedEndpoints:uniq.filter(x=>x.source==='route-scan').length}};}
function apiJsonPath(obj,path){if(!path)return obj;return String(path).split('.').reduce((v,k)=>v==null?undefined:v[k],obj);}
function apiTypeOk(v,t){if(t==='object')return v!==null&&typeof v==='object'&&!Array.isArray(v);if(t==='array')return Array.isArray(v);if(t==='integer')return Number.isInteger(v);if(t==='number')return typeof v==='number';if(t==='boolean')return typeof v==='boolean';if(t==='string')return typeof v==='string';return true;}
function apiValidateSchema(value,schema,root,path='$'){schema=apiResolveSchema(root,schema);const failures=[];if(schema.type&&!apiTypeOk(value,schema.type))failures.push(`${path}: expected ${schema.type}`);if(schema.required&&apiObj(schema.properties)){for(const k of apiArray(schema.required))if(value==null||value[k]===undefined)failures.push(`${path}.${k}: required`);}if(schema.properties&&value&&typeof value==='object'&&!Array.isArray(value)){for(const [k,ss] of Object.entries(schema.properties)){if(value[k]!==undefined)failures.push(...apiValidateSchema(value[k],ss,root,`${path}.${k}`));}}if(schema.items&&Array.isArray(value))value.forEach((v,i)=>failures.push(...apiValidateSchema(v,schema.items,root,`${path}[${i}]`)));return failures;}
function apiHeadersMap(v){const o={};for(const [k,val] of Object.entries(apiObj(v)))o[k.toLowerCase()]=String(val);return o;}
function apiCommand(environment,url,method,headers,body){const h=Object.entries(apiObj(headers)).map(([k,v])=>`-H "${String(k).replace(/"/g,'\\"')}: ${String(v).replace(/"/g,'\\"')}"`).join(' ');const data=body===undefined?'':` --data '${JSON.stringify(body).replace(/'/g,"'\\''")}'`;const code=environment&&/windows|desktop/i.test(environment)?`curl.exe -sS -D - -o - -X ${method} ${h}${data} "${String(url).replace(/"/g,'\\"')}"`:`curl -sS -D - -o - -X ${method} ${h}${data} "${String(url).replace(/"/g,'\\"')}"`;return code;}
function apiParseCurl(raw){const text=String(raw??'');const matches=[...text.matchAll(/HTTP\/\d(?:\.\d)?\s+(\d{3})[^\r\n]*\r?\n([\s\S]*?)(?:\r?\n\r?\n)([\s\S]*)/g)];const m=matches[matches.length-1];if(!m)return{status:null,headers:{},bodyText:text,body:null};const headers={};for(const line of m[2].split(/\r?\n/)){const i=line.indexOf(':');if(i>0)headers[line.slice(0,i).trim().toLowerCase()]=line.slice(i+1).trim();}let bodyText=m[3].trim(),body=null;try{body=JSON.parse(bodyText);}catch{}return{status:Number(m[1]),headers,bodyText,body};}
function apiAssert(test,response){const failures=[];const statuses=apiArray(test.expectedStatuses).length?apiArray(test.expectedStatuses):[test.expectedStatus||200];if(response.status===null)failures.push('No HTTP status received');else if(!statuses.includes(response.status))failures.push(`status: expected ${statuses.join('/')} got ${response.status}`);for(const [k,v] of Object.entries(apiObj(test.expectedHeaders)))if(String(response.headers[k.toLowerCase()]||'')!==String(v))failures.push(`header ${k}: expected ${v}`);if(test.expectContentType){const ct=response.headers['content-type']||'';if(!ct.toLowerCase().includes(String(test.expectContentType).toLowerCase()))failures.push(`content-type: expected ${test.expectContentType}`);}for(const [p,v] of Object.entries(apiObj(test.expectedBody)))if(JSON.stringify(apiJsonPath(response.body,p))!==JSON.stringify(v))failures.push(`body.${p}: expected ${JSON.stringify(v)}`);if(test.responseSchema&&response.body!==null)failures.push(...apiValidateSchema(response.body,test.responseSchema,test.responseSchema,'$.response'));return failures;}
async function runUniversalApiContractTesting(options={}){if(typeof options.execute!=='function')return{available:false,error:'No command executor supplied.'};const baseUrl=String(options.baseUrl||'').replace(/\/$/,'');let discovery=options.discovery||null;if(!discovery&&options.discover!==false)discovery=await apiDiscover(options);let contracts=apiArray(options.contracts);if(!contracts.length)contracts=apiArray(discovery?.contracts);contracts=contracts.map(c=>({...c}));if(options.maxEndpoints)contracts=contracts.slice(0,Math.max(1,Number(options.maxEndpoints)));const results=[];for(const c of contracts){if(['POST','PUT','PATCH','DELETE'].includes(c.method)&&options.allowMutations!==true)continue;const path=String(c.path||'/').replace(/\{([^}]+)\}/g,'test');const url=apiJoin(baseUrl,path);let body=c.requestBodySample;if(body===undefined&&c.requestSchema)body=apiSample(c.requestSchema);const headers={Accept:'application/json',...(c.headers||{})};if(body!==undefined)headers['Content-Type']='application/json';const ev=await (async()=>{const started=Date.now();try{return{ok:true,raw:await options.execute(apiCommand(options.environment||'',url,c.method,headers,body),{phase:'api-contract',timeoutMs:options.timeoutMs||20000}),elapsedMs:Date.now()-started};}catch(e){return{ok:false,error:e?.message||String(e),elapsedMs:Date.now()-started};}})();const raw=ev.raw?.stdout||ev.raw?.output||ev.raw?.result||ev.raw||'';const response=ev.ok?apiParseCurl(raw):{status:null,headers:{},bodyText:'',body:null};const failures=ev.ok?apiAssert({...c,responseSchema:apiResolveSchema(c.responseSchema||c.responses?.[String(response.status)]?.content?.['application/json']?.schema||null,c)},response):[apiRedact(ev.error||'request failed')];results.push({endpoint:`${c.method} ${c.path}`,source:c.source,operationId:c.operationId,status:response.status,elapsedMs:ev.elapsedMs,passed:failures.length===0,failures:failures.map(apiRedact),request:{method:c.method,url:apiRedact(url),body:c.method==='GET'||c.method==='HEAD'?undefined:body},response:{headers:response.headers,body:response.body===null?undefined:response.body}});}
// Safe negative tests: only GET unknown-route and schema-required-field checks; mutation negatives require explicit opt-in.
if(options.negativeTests!==false){const gets=contracts.filter(c=>c.method==='GET').slice(0,Math.max(1,Number(options.maxNegativeTests??2)));for(const c of gets){const bad=apiJoin(baseUrl,`${String(c.path||'/').replace(/\/$/,'')}/__agent_not_found__`);const ev=await options.execute(apiCommand(options.environment||'',bad,'GET',{Accept:'application/json'}),{phase:'api-negative',timeoutMs:options.timeoutMs||20000});const raw=ev?.stdout||ev?.output||ev?.result||ev||'';const r=apiParseCurl(raw);const passed=[404,410].includes(Number(r.status));results.push({endpoint:`GET ${bad}`,negative:true,status:r.status,passed,failures:passed?[]:[`negative route expected 404/410 got ${r.status}`],request:{method:'GET',url:apiRedact(bad)}});}}
const failed=results.filter(r=>!r.passed);return{available:true,version:UNIVERSAL_API_TESTING_VERSION,discovery,contracts:contracts.length,results,status:failed.length?'failed':'passed',summary:{total:results.length,passed:results.length-failed.length,failed:failed.length,negative:results.filter(r=>r.negative).length,mutationsAllowed:options.allowMutations===true},capability:'empirical-api-contract-and-integration-testing'};}
if(typeof module!=='undefined')module.exports={UNIVERSAL_API_TESTING_VERSION,apiDiscover,runUniversalApiContractTesting,apiExtractOpenApi,apiExtractRoutes,apiValidateSchema,apiSample};
